export const dataFinding = [
  {
   title: 'Otváranie očí',
   data: 'openingEyes',
   style: {marginBottom: 20,  backgroundColor: '#d5dce1'},
   key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Verb. kontakt',
    data: 'verbalContact',
    style: {marginBottom: 20, backgroundColor: '#d5dce1'},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Motorika',
    data: 'motorSkills',
    style: {marginBottom: 20, backgroundColor: '#d5dce1'},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Očné reflexy',
    data: 'eyeReflexes',
    style: {marginBottom: 20},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Bolesť',
    data: 'pain',
    style: {marginBottom: 20},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Brucho',
    data: 'belly',
    style: {marginBottom: 20},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Dýchacie cesty',
    data: 'airways',
    style: {marginBottom: 20, backgroundColor: '#a5ddfa'},
    styleChilldren: {backgroundColor: '#a5ddfa'}, 
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Dýchanie',
    data: 'breathing',
    style: {marginBottom: 20, backgroundColor: '#a5ddfa'},
    styleChilldren: {backgroundColor: '#a5ddfa'}, 
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Auskultačný nález',
    data: 'auscultationFinding',
    style: {marginBottom: 20, backgroundColor: '#a5ddfa'},
    styleChilldren: {backgroundColor: '#a5ddfa'}, 
    key: Math.random().toString(12).substring(0)
  }, 
  {
    title: 'Neurologický	 nález',
    data: 'neurologicalFinding',
    style: {marginBottom: 20, backgroundColor: '#d5dde1'},
    styleChilldren: {backgroundColor: '#d5dde1'}, 
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Cirkulácia',
    subTitle: ['Pulz', 'cent.', 'perit.'],
    data: 'circulation',
    style: {marginBottom: 20, backgroundColor: '#f7b6d7'},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Auskultačný nález',
    subTitle: 'Akcia srdca',
    data: 'auscultationFindingPink',
    style: {marginBottom: 20, backgroundColor: '#f7b6d7'},
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Koža',
    data: 'leather',
    style: {marginBottom: 20, backgroundColor: '#f7b6d7'},
    styleChilldren: {backgroundColor: '#f7b6d7'}, 
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'Auskultačný nález',
    data: 'auscultationFinding',
    style: {marginBottom: 20, backgroundColor: '#a5ddfa'},
    styleChilldren: {backgroundColor: '#a5ddfa'}, 
    key: Math.random().toString(12).substring(0)
  },
  {
    title: 'auscultationFinding',
    data: 'eyeReflexes',
    // style: {marginBottom: 31},
    // style: {marginBottom: 31},
    key: Math.random().toString(12).substring(0)
  },
]
export const timeData = [
  { title: 'Čas', engTitle: 'time'},
  { title: 'Systl. TK', subTitle: 'Torr', style: {backgroundColor: '#f7b6d7'}, engTitle: 'syst' },
  { title: 'Diast. TK', subTitle: 'Torr',  style: {backgroundColor: '#f7b6d7'}, engTitle: 'diast' },
  { title: 'SF (HR)', subTitle: 'min', style: {backgroundColor: '#f7b6d7'}, engTitle: 'sf' },
  { title: 'DF (RR)', subTitle: 'min', style: {backgroundColor: '#a5ddfa'}, engTitle: 'df' },
  { title: 'DO (TV)', subTitle: 'ml', style: {backgroundColor: '#a5ddfa'}, engTitle: 'do' },
  { title: 'O saturacia', subTitle: '%', style: {backgroundColor: '#a5ddfa'}, engTitle: 'saturacia' },
  { title: 'Glyk.', subTitle: 'mmo|/|', engTitle: 'glyk' },
  { title: 'TT', subTitle: 'C', engTitle: 'tt' },
  { title: 'GCS', style: {backgroundColor: '#d5dde1'}, engTitle: 'gcs' },
  { title: 'TS', subTitle: '', engTitle: 'ts' },
  { title: '', style: {marginBottom: 15}, engTitle: 'add' },
]
export const upvData = [
  { title: 'UPV', style: {backgroundColor: '#a5ddfa'}, engTitle: 'upv'},
  { title: 'Masáž', subTitle: '', style: {backgroundColor: '#f7b6d7'}, engTitle: 'massage' },
  { title: 'Defibrilácia', subTitle: '',  style: {backgroundColor: '#f7b6d7'}, engTitle: 'defibrillation' },
  { title: 'Pace-maker', subTitle: 'Ⓟ', style: {backgroundColor: '#f7b6d7'}, engTitle: 'paceMaker' },
  { title: 'Transport', subTitle: 'T', style: {marginBottom: 15 }, engTitle: 'transport' },
]
export const timeTable = {
  time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: "2-digit", second: "2-digit", hour12: false }),
  syst: '',
  diast: '',
  sf: '',
  df: '',
  do: '',
  saturacia: '',
  glyk: '',
  tt: '',
  gcs: '',
  ts: '',
  add: {key: '', value: ''},
  id: ''
}
export const upvTable = {
  upv: '',
  massage: '',
  diast: '',
  defibrillation: '',
  paceMaker: '',
  transport: '',
}
export const FRONT_MAP = [
  {
    id: '0',
    name: 'Left Foot',
    shape: 'rectangle',
    x2: 150,
    y2: 630,
    x1: 95,
    y1: 597,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '1',
    name: 'Right Foot',
    shape: 'rectangle',
    x2: 210,
    y2: 630,
    x1: 155,
    y1: 597,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '2',
    name: 'Left Ankle',
    shape: 'rectangle',
    x2: 150,
    y2: 597,
    x1: 110,
    y1: 580,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '3',
    name: 'Right Ankle',
    shape: 'rectangle',
    x2: 195,
    y2: 597,
    x1: 155,
    y1: 580,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '4',
    name: 'Left Shin',
    shape: 'rectangle',
    x2: 150,
    y2: 580,
    x1: 110,
    y1: 480,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '5',
    name: 'Right Shin',
    shape: 'rectangle',
    x2: 195,
    y2: 580,
    x1: 155,
    y1: 480,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '6',
    name: 'Left Knee',
    shape: 'rectangle',
    x2: 145,
    y2: 480,
    x1: 110,
    y1: 425,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '7',
    name: 'Right Knee',
    shape: 'rectangle',
    x2: 195,
    y2: 480,
    x1: 158,
    y1: 425,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '8',
    name: 'Left Thigh',
    shape: 'rectangle',
    x2: 150,
    y2: 425,
    x1: 95,
    y1: 310,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '9',
    name: 'Right Thigh',
    shape: 'rectangle',
    x2: 209,
    y2: 425,
    x1: 154,
    y1: 310,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '10',
    name: 'Groin area',
    shape: 'rectangle',
    x2: 184,
    y2: 340,
    x1: 120,
    y1: 290,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '11',
    name: 'Stomach',
    shape: 'rectangle',
    x2: 205,
    y2: 290,
    x1: 100,
    y1: 220,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '12',
    name: 'Chest',
    shape: 'rectangle',
    x2: 205,
    y2: 220,
    x1: 100,
    y1: 130,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '13',
    name: 'Left Hand',
    shape: 'rectangle',
    x2: 65,
    y2: 370,
    x1: 10,
    y1: 310,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '14',
    name: 'Right Hand',
    shape: 'rectangle',
    x2: 292,
    y2: 370,
    x1: 237,
    y1: 310,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '15',
    name: 'Left Wrist',
    shape: 'rectangle',
    x2: 65,
    y2: 310,
    x1: 30,
    y1: 295,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '16',
    name: 'Right Wrist',
    shape: 'rectangle',
    x2: 272,
    y2: 310,
    x1: 237,
    y1: 295,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '17',
    name: 'Left Forearm',
    shape: 'rectangle',
    x2: 90,
    y2: 295,
    x1: 40,
    y1: 230,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '18',
    name: 'Right Forearm',
    shape: 'rectangle',
    x2: 265,
    y2: 295,
    x1: 215,
    y1: 230,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '19',
    name: 'Left Arm',
    shape: 'rectangle',
    x2: 100,
    y2: 230,
    x1: 60,
    y1: 155,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '20',
    name: 'Right Arm',
    shape: 'rectangle',
    x2: 245,
    y2: 230,
    x1: 205,
    y1: 155,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '21',
    name: 'Left Shoulder',
    shape: 'rectangle',
    x2: 120,
    y2: 155,
    x1: 70,
    y1: 120,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '22',
    name: 'Right Shoulder',
    shape: 'rectangle',
    x2: 237,
    y2: 155,
    x1: 187,
    y1: 120,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '23',
    name: 'Neck',
    shape: 'rectangle',
    x2: 187,
    y2: 130,
    x1: 120,
    y1: 103,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '24',
    name: 'Face',
    shape: 'rectangle',
    x2: 187,
    y2: 103,
    x1: 120,
    y1: 58,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '25',
    name: 'Head',
    shape: 'rectangle',
    x2: 187,
    y2: 58,
    x1: 120,
    y1: 28,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '26',
    name: 'SmallLeftCircle',
    shape: 'rectangle',
    x2: 100,
    y2: 100,
    x1: 50,
    y1: 65,
    // prefill: 'green',
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '27',
    name: 'SmallRightCircle',
    shape: 'rectangle',
    x2: 250,
    y2: 100,
    x1: 201,
    y1: 65,
    // prefill: 'green',
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '28',
    name: 'BigLeftCircle',
    shape: 'rectangle',
    x2: 100,
    y2: 56,
    x1: 50,
    y1: 21,
    // prefill: 'green',
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '29',
    name: 'BigRightCircle',
    shape: 'rectangle',
    x2: 250,
    y2: 56,
    x1: 201,
    y1: 21,
    // prefill: 'green',
    fill: { sine: false, fillWith: '' },
  },
];

export const BACK_MAP = [
  {
    id: '0',
    name: 'Left Heel',
    shape: 'rectangle',
    x2: 150,
    y2: 630,
    x1: 95,
    y1: 570,
    // fill: require('../../assets/X.png'),
    fill: { sine: false, fillWith: '' },
    prefill: 'green',
  },
  {
    id: '1',
    name: 'Right Heel',
    shape: 'rectangle',
    x2: 210,
    y2: 630,
    x1: 155,
    y1: 570,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '2',
    name: 'Left Shin',
    shape: 'rectangle',
    x2: 150,
    y2: 570,
    x1: 110,
    y1: 470,
    // prefill: getRandomColor(),
    // fill: require('../../assets/X.png'),
    fill: { sine: false, fillWith: '' }
  },
  {
    id: '3',
    name: 'Right Shin',
    shape: 'rectangle',
    x2: 195,
    y2: 570,
    x1: 155,
    y1: 470,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '4',
    name: 'Left Thigh',
    shape: 'rectangle',
    x2: 150,
    y2: 470,
    x1: 93,
    y1: 350,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '5',
    name: 'Right Thigh',
    shape: 'rectangle',
    x2: 209,
    y2: 470,
    x1: 154,
    y1: 350,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '6',
    name: 'Left Buttock',
    shape: 'circle',
    x1: 90,
    y1: 285,
    radius: 70,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '7',
    name: 'Right Buttock',
    shape: 'circle',
    x1: 145,
    y1: 285,
    radius: 70,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '8',
    name: 'Loin',
    shape: 'rectangle',
    x2: 205,
    y2: 290,
    x1: 100,
    y1: 240,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '9',
    name: 'Back',
    shape: 'rectangle',
    x2: 205,
    y2: 240,
    x1: 100,
    y1: 110,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '10',
    name: 'Left Hand',
    shape: 'rectangle',
    x2: 65,
    y2: 370,
    x1: 10,
    y1: 305,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '11',
    name: 'Right Hand',
    shape: 'rectangle',
    x2: 292,
    y2: 370,
    x1: 237,
    y1: 305,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '12',
    name: 'Left Forearm',
    shape: 'rectangle',
    x2: 90,
    y2: 305,
    x1: 40,
    y1: 230,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '13',
    name: 'Right Forearm',
    shape: 'rectangle',
    x2: 265,
    y2: 305,
    x1: 215,
    y1: 230,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  
  {
    id: '14',
    name: 'Left Elbow',
    shape: 'rectangle',
    x2: 95,
    y2: 230,
    x1: 55,
    y1: 210,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '15',
    name: 'Right Elbow',
    shape: 'rectangle',
    x2: 250,
    y2: 230,
    x1: 210,
    y1: 210,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '16',
    name: 'Left Arm',
    shape: 'rectangle',
    x2: 100,
    y2: 210,
    x1: 60,
    y1: 150,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '17',
    name: 'Right Arm',
    shape: 'rectangle',
    x2: 245,
    y2: 210,
    x1: 205,
    y1: 150,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '18',
    name: 'Left Shoulder',
    shape: 'rectangle',
    x2: 120,
    y2: 150,
    x1: 70,
    y1: 110,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '19',
    name: 'Right Shoulder',
    shape: 'rectangle',
    x2: 237,
    y2: 150,
    x1: 187,
    y1: 110,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '20',
    name: 'Neck',
    shape: 'rectangle',
    x2: 187,
    y2: 110,
    x1: 120,
    y1: 90,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '21',
    name: 'BackOfTheHead',
    shape: 'rectangle',
    x2: 187,
    y2: 90,
    x1: 120,
    y1: 50,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
  {
    id: '22',
    name: 'TopOfTheHead',
    shape: 'rectangle',
    x2: 187,
    y2: 50,
    x1: 120,
    y1: 22,
    // prefill: getRandomColor(),
    fill: { sine: false, fillWith: '' },
  },
];